name: Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]



    
jobs:



    deploy:
        name: Wait for Deploy
        runs-on: ubuntu-latest
        steps:
          - name: Wait for Render Deployment
            uses: Bounceapp/render-action@0.7.0
            with:
              render-token: ${{ secrets.RENDER_TOKEN }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              service-id: srv-cidgk0lgkuvncfbusu5g
              retries: 20
              wait: 16000
              sleep: 30000